<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>About me </title>
</head>

<body>
  <center>
    <h1>About me </h1>
    <br/>
    <img src="/hw3/public/img/few.jpg" width=40%/>
    <br/><br/>
    <h2>นรนิติ  โยธา</h2>
    <h2>๕๙๐๖๑๐๖๓๐</h2>
    <body bgcolor="#FF00F0"></body>
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
  </center>
</body>

</html>